- Developer:
    - GitHub:
        - abbr: GH
          href: https://github.com/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/github-light.png
    - Dashboardicons:
        - abbr: DI
          href: https://dashboardicons.com
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/homarr.png
    - MotU-Web:
        - abbr: MW
          href: https://motu.fritz.box/

- Social:
    - Reddit:
        - abbr: RDT
          href: https://reddit.com/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/reddit.png
    - Facebook:
        - abbr: FB
          href: https://facebook.com/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/facebook.png
    - Instagram:
        - abbr: IG
          href: https://instagram.com/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/instagram.png

- Media:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/youtube.png
    - Watch2Gether:
        - abbr: W2G
          href: https://w2g.tv/
          icon: https://w2g.tv/assets/up_/img/icons/256.png
    - Joyn:
        - abbr: JY
          href: https://joyn.de
          icon: https://m.media-amazon.com/images/I/71Vw5JBhcEL.png

- Automation:
    - Open WebUI:
        - abbr: OI
          href: https://chat.fritz.box
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/open-webui-light.png
    - n8n:
        - abbr: N8N
          href: https://n8n.fritz.box
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/n8n.png

- Shopping:
    - Amazon:
        - abbr: AMZ
          href: https://amazon.de/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/amazon.png
    - Idealo:
        - abbr: IDE
          href: https://idealo.de/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/idealo.png
    - Kleinanzeigen:
        - abbr: KK
          href: https://kleinanzeigen.de/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/kleinanzeigen.png
    - Ebay:
        - abbr: EBAY
          href: https://ebay.de/
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/ebay.png
    - OTTO:
        - abbr: OTTO
          href: https://otto.de/
          icon: https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/c6/d6/49/c6d64987-3993-f908-4ec8-4e6e6b9ff9b2/app-icon-0-1x_U007emarketing-0-7-0-85-220.png/512x512bb.jpg
    - Bring!:
        - abbr: BRG
          href: https://web.getbring.com/app/lists/0
          icon: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%2Fid%2FOIP.3_2mgNzIXTfjWHrdY-KLRgAAAA%3Fpid%3DApi&f=1&ipt=0afaf4de5023f0268c89259d5ea98b72e6fc37263065cddc20cc9dd86ab39dd0

- Gaming:
    - BoardGameArena:
        - abbr: BGA
          href: https://boardgamearena.com/
          icon: https://doc.boardgamearena.com/images/thumb/e/e4/Logo_without_title.png/800px-Logo_without_title.png
    - Melodice:
        - abbr: MEL
          href: https://melodice.com/
          icon: https://tse2.mm.bing.net/th/id/OIP.Kpn2jStgG0OUTqQ89JHeBgAAAA%3Fpid%3DApi

- Versicherungen:
    - AXA:
        - abbr: AXA
          href: https://entry.axa.de/sls-myaxa/auth
          icon: https://logos-world.net/wp-content/uploads/2020/07/AXA-Logo-700x394.png
    - Allianz:
        - abbr: ALZ
          href: https://cim.allianz.de/ui/login/de/allianz/start
          icon: https://static.vecteezy.com/system/resources/previews/026/555/095/non_2x/allianz-logo-transparent-free-png.png
